### ISSUE TITLE
Background - "Local" and "multiple" shows only the first picture 

### ISSUE THREAD

**Issue by TheMadav** [SixBytesUnder/infoboard#2]
Adding a directory with multiple pictures as background will only show the first picture. The problem is within the for-loop. As it is executed for each element, the if-condition is never met and the else-condition will break and return the first file. A dirty fix would simple eliminate the for-loop, but I guess it is needed to traverse into sub-folders, right?

```
for (let dir of dirList) {
		let fullPath = path.join(startPath, dir)
		if (fs.statSync(fullPath).isDirectory()) {
			files = glob.sync('**/*.+(jpg|jpeg)', {
				cwd: fullPath,
				nocase: true,
				realpath: true
			})
			if (files.length > 0) {
				// clean paths to be relative
				let filesShort = files.map(function (x) { return x.replace(normalizedMainDir, '') })
				return filesShort
			}
		} else {
			// return that one file
			return [dir]
		}
	}
```

**Comment by SixBytesUnder** [comment]
Hi @TheMadav 
Can you give me a bit more details on your scenario? I have a folder with multiple folders and other subfolders in it and I don't have this issue.
Is your folder only with images directly in it, and not any subfolders?

**Comment by TheMadav** [comment]
Sure - I have one folder with all background images without subfolders

> /backgrounds
>    --> background1.jpg
>    --> background2.jpg

The API returns only the first image. After I removed the for-Loop both images were returned.

**Comment by SixBytesUnder** [comment]
Thanks for this. It seems easily reproducible. I'll look into it later today.

**Comment by SixBytesUnder** [comment]
Hi @TheMadav 
This proved to be a tricky one, but I figured it out, so that it works in all scenarios.
Just pushed the code up, try it and let me know if it worked for you.

**Comment by TheMadav** [comment]
Hi @SixBytesUnder 

took a while - but yes it works - now I have only to merge all my changes 😃 

Thanks!

**Comment by SixBytesUnder** [comment]
Not sure why, but Nuxt sometimes complains without any real reason after updates when you run `npm run build`. If that happens for you, just move your .env file to a different location, delete the whole thing and pull the latest version from Git.
